Repository ExploreNYM/bash-tool, pull requests merged in 2023-07, with the labels that each got.

#7 2 invalid username breaks tool
  scripts/check-vps.sh
Labels: bug

#10 8 transfer text to json
  README.md
  scripts/check-vps.sh
  scripts/cleanup.sh
  scripts/explore-nym.sh
  scripts/mixnode/backup.sh
  scripts/mixnode/change-details.sh
  scripts/mixnode/install.sh
  scripts/mixnode/migrate.sh
  scripts/mixnode/status.sh
  scripts/mixnode/tool.sh
  scripts/mixnode/update.sh
  text/backup.json
  text/change-details.json
  text/check-vps.json
  text/install.json
  text/migrate.json
  text/status.json
  text/tool.json
  text/update.json
Labels: enhancement

#12 feat: added ci for the json files
  .ci/backup-schema.json
  .ci/change-details-schema.json
  .ci/check-vps-schema.json
  .ci/install-schema.json
  .ci/migrate-schema.json
  .ci/status-schema.json
  .ci/tool-schema.json
  .ci/update-schema.json
  .ci/validate.py
  .github/workflows/translations.yml
  scripts/check-vps.sh
  text/check-vps.json
Labels: enhancement

#14 13 portuguese translation
  .ci/install-schema.json
  README.md
  scripts/explore-nym.sh
  text/backup.json
  text/change-details.json
  text/check-vps.json
  text/install.json
  text/migrate.json
  text/status.json
  text/tool.json
  text/update.json
Labels: translation

#16 Contributting tutorial
  README.md
Labels: documentation

#15 refactor: formatted json files
  text/backup.json
  text/change-details.json
  text/check-vps.json
  text/install.json
  text/migrate.json
  text/status.json
  text/tool.json
  text/update.json
Labels: enhancement

#19 add: french translation
  text/backup.json
  text/change-details.json
  text/check-vps.json
  text/install.json
  text/migrate.json
  text/status.json
  text/tool.json
  text/update.json
Labels: translation

#20 French to menu
  README.md
  scripts/check-vps.sh
  scripts/explore-nym.sh
  scripts/mixnode/backup.sh
  scripts/mixnode/change-details.sh
  scripts/mixnode/install.sh
  scripts/mixnode/migrate.sh
  scripts/mixnode/status.sh
  scripts/mixnode/tool.sh
  scripts/mixnode/update.sh
Labels: translation
